version: '3.3'

services:
  consul:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  consul-agent:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
    command: "agent -dev -join=consul"

  consul-agent-1:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
    command: "agent -dev -join=consul"

  micro:
    command: --registry_address=consul:8500 api --handler=proxy
    image: microhq/micro:latest
    links:
      - consul
      - api
    ports:
      - "8080:8080"
  api:
    build: ./api/petstore
    command: --registry_address=consul:8500
    environment:
      GOSUMDB: 'off'
      SECRET: 'purple monkey dishwasher'
    links:
      - consul
      - user
      - store
      - pet
  user:
    build: ./srv/user
    command: --registry_address=consul:8500
    environment:
      GOSUMDB: 'off'
      DB_USER: 'root'
      DB_PASSWORD: 'w31lh3313d'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'user'
    links:
      - consul
      - db
  store:
    build: ./srv/store
    command: --registry_address=consul:8500
    environment:
      GOSUMDB: 'off'
      DB_USER: 'root'
      DB_PASSWORD: 'w31lh3313d'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'store'
    links:
      - consul
      - db
  pet:
    build: ./srv/pet
    command: --registry_address=consul:8500
    environment:
      GOSUMDB: 'off'
      DB_USER: 'root'
      DB_PASSWORD: 'w31lh3313d'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'pet'
    links:
      - consul
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'kl3pt0man1a'
      MYSQL_ROOT_PASSWORD: 'w31lh3313d'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./tools/migrate-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  petstore: