// Code generated by protoc-gen-go.
// source: srv/store/proto/order.proto
// DO NOT EDIT!

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	srv/store/proto/order.proto

It has these top-level messages:
	InventoryRequest
	InventoryResponse
	PlaceRequest
	PlaceResponse
	GetRequest
	GetResponse
	DeleteRequest
	DeleteResponse
*/
package store

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type InventoryRequest struct {
}

func (m *InventoryRequest) Reset()         { *m = InventoryRequest{} }
func (m *InventoryRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryRequest) ProtoMessage()    {}

type InventoryResponse struct {
	Inventory map[string]int64 `protobuf:"bytes,1,rep,name=inventory" json:"inventory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *InventoryResponse) Reset()         { *m = InventoryResponse{} }
func (m *InventoryResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryResponse) ProtoMessage()    {}

func (m *InventoryResponse) GetInventory() map[string]int64 {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type PlaceRequest struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PetId    int64  `protobuf:"varint,2,opt,name=pet_id" json:"pet_id,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	ShipDate string `protobuf:"bytes,4,opt,name=ship_date" json:"ship_date,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	Complete bool   `protobuf:"varint,6,opt,name=complete" json:"complete,omitempty"`
}

func (m *PlaceRequest) Reset()         { *m = PlaceRequest{} }
func (m *PlaceRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceRequest) ProtoMessage()    {}

type PlaceResponse struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PetId    int64  `protobuf:"varint,2,opt,name=pet_id" json:"pet_id,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	ShipDate string `protobuf:"bytes,4,opt,name=ship_date" json:"ship_date,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	Complete bool   `protobuf:"varint,6,opt,name=complete" json:"complete,omitempty"`
}

func (m *PlaceResponse) Reset()         { *m = PlaceResponse{} }
func (m *PlaceResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceResponse) ProtoMessage()    {}

type GetRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}

type GetResponse struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PetId    int64  `protobuf:"varint,2,opt,name=pet_id" json:"pet_id,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	ShipDate string `protobuf:"bytes,4,opt,name=ship_date" json:"ship_date,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	Complete bool   `protobuf:"varint,6,opt,name=complete" json:"complete,omitempty"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}

type DeleteRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

func init() {
}
