// Code generated by protoc-gen-go.
// source: api/petstore/proto/petstore.proto
// DO NOT EDIT!

/*
Package petstore is a generated protocol buffer package.

It is generated from these files:
	api/petstore/proto/petstore.proto

It has these top-level messages:
*/
package petstore

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

func init() {
}
