// Code generated by protoc-gen-go.
// source: srv/user/proto/user.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	srv/user/proto/user.proto

It has these top-level messages:
	UserRequest
	UserResponse
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	GetRequest
	GetResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
*/
package user

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type UserRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName  string `protobuf:"bytes,3,opt,name=first_name" json:"first_name,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=last_name" json:"last_name,omitempty"`
	Email      string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Password   []byte `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Phone      string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
	UserStatus int64  `protobuf:"varint,8,opt,name=userStatus" json:"userStatus,omitempty"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}

type UserResponse struct {
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}

type LoginResponse struct {
	Success string `protobuf:"bytes,1,opt,name=success" json:"success,omitempty"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}

type LogoutRequest struct {
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}

type GetRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}

type GetResponse struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName  string `protobuf:"bytes,3,opt,name=first_name" json:"first_name,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=last_name" json:"last_name,omitempty"`
	Email      string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Password   []byte `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Phone      string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
	UserStatus int64  `protobuf:"varint,8,opt,name=userStatus" json:"userStatus,omitempty"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}

type UpdateRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName  string `protobuf:"bytes,3,opt,name=first_name" json:"first_name,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=last_name" json:"last_name,omitempty"`
	Email      string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Password   []byte `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Phone      string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
	UserStatus int64  `protobuf:"varint,8,opt,name=userStatus" json:"userStatus,omitempty"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}

type DeleteRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

func init() {
}
