-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 20:23:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pet` ;

-- -----------------------------------------------------
-- Table `pet`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categories_id_uindex` (`id` ASC) VISIBLE,
  INDEX `categories_name_index` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pet`.`pet_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet`.`pet_tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `petId` INT(11) NOT NULL,
  `tagId` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pet`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet`.`pets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoryId` INT(11) NOT NULL,
  `status` VARCHAR(128) NOT NULL DEFAULT 'pending',
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pets_id_index` (`id` ASC) VISIBLE,
  INDEX `pets_name_index` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pet`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet`.`photos` (
  `id` INT(11) NULL DEFAULT NULL,
  `petId` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `filename` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pet`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tags_id_index` (`id` ASC) VISIBLE,
  INDEX `tags_name_index` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `petId` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT '0',
  `shipDate` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(64) NULL DEFAULT NULL,
  `complete` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `order_id_index` (`id` ASC) VISIBLE,
  INDEX `order_status_index` (`status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `firstName` VARCHAR(128) NOT NULL,
  `lastName` VARCHAR(128) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(64) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `userStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_index` (`username` ASC) VISIBLE,
  INDEX `email_index` (`email` ASC) VISIBLE,
  INDEX `user_id_index` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
