// Code generated by protoc-gen-go.
// source: srv/pet/proto/pet.proto
// DO NOT EDIT!

/*
Package pet is a generated protocol buffer package.

It is generated from these files:
	srv/pet/proto/pet.proto

It has these top-level messages:
	AddRequest
	AddResponse
	UpdateRequest
	UpdateResponse
	ByStatusRequest
	ByStatusResponse
	ByIDRequest
	ByIDResponse
	DeleteRequest
	DeleteResponse
	UploadImageRequest
	UploadImageResponse
	Pet
	Category
	Tag
	PhotoURL
*/
package pet

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type AddRequest struct {
	Pet *Pet `protobuf:"bytes,1,opt,name=pet" json:"pet,omitempty"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}

func (m *AddRequest) GetPet() *Pet {
	if m != nil {
		return m.Pet
	}
	return nil
}

type AddResponse struct {
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}

type UpdateRequest struct {
	Pet *Pet `protobuf:"bytes,1,opt,name=pet" json:"pet,omitempty"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}

func (m *UpdateRequest) GetPet() *Pet {
	if m != nil {
		return m.Pet
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}

type ByStatusRequest struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ByStatusRequest) Reset()         { *m = ByStatusRequest{} }
func (m *ByStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ByStatusRequest) ProtoMessage()    {}

type ByStatusResponse struct {
	Pets []*Pet `protobuf:"bytes,1,rep,name=pets" json:"pets,omitempty"`
}

func (m *ByStatusResponse) Reset()         { *m = ByStatusResponse{} }
func (m *ByStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ByStatusResponse) ProtoMessage()    {}

func (m *ByStatusResponse) GetPets() []*Pet {
	if m != nil {
		return m.Pets
	}
	return nil
}

type ByIDRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ByIDRequest) Reset()         { *m = ByIDRequest{} }
func (m *ByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByIDRequest) ProtoMessage()    {}

type ByIDResponse struct {
	Pet *Pet `protobuf:"bytes,1,opt,name=pet" json:"pet,omitempty"`
}

func (m *ByIDResponse) Reset()         { *m = ByIDResponse{} }
func (m *ByIDResponse) String() string { return proto.CompactTextString(m) }
func (*ByIDResponse) ProtoMessage()    {}

func (m *ByIDResponse) GetPet() *Pet {
	if m != nil {
		return m.Pet
	}
	return nil
}

type DeleteRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

type UploadImageRequest struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}

type UploadImageResponse struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}

type Pet struct {
	Id        int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status    string      `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Category  *Category   `protobuf:"bytes,4,opt,name=category" json:"category,omitempty"`
	Tags      []*Tag      `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	PhotoUrls []*PhotoURL `protobuf:"bytes,6,rep,name=photo_urls" json:"photo_urls,omitempty"`
}

func (m *Pet) Reset()         { *m = Pet{} }
func (m *Pet) String() string { return proto.CompactTextString(m) }
func (*Pet) ProtoMessage()    {}

func (m *Pet) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Pet) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Pet) GetPhotoUrls() []*PhotoURL {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

type Category struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}

type Tag struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}

type PhotoURL struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Caption  string `protobuf:"bytes,2,opt,name=caption" json:"caption,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Filename string `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
}

func (m *PhotoURL) Reset()         { *m = PhotoURL{} }
func (m *PhotoURL) String() string { return proto.CompactTextString(m) }
func (*PhotoURL) ProtoMessage()    {}

func init() {
}
